Cache dependecies
NodeFactoryIo/vedran pull request #16
Opened 2020-09-11 15:26 UTC by MakMuftic

Cache dependencies on Github actions PR:
- add dependencies caching setup inside config file

closes #15

2020-09-11 17:52 UTC, mpetrunic requested changes
You should checkout code first so you get go.sum file

2020-09-16 11:14 UTC, MakMuftic commented
@mpetrunic also just fixed my nick inside code owners here

2020-09-16 11:21 UTC, mpetrun5 approved these changes

2020-09-16 11:45 UTC, mpetrunic approved these changes

2020-09-16 11:45 UTC, merged