Mmuftic/cli
NodeFactoryIo/vedran pull request #23
Opened 2020-09-17 13:19 UTC by MakMuftic

### Changes

Expanded `start` CLI command with all defined flags 

- `auth-secret`
- `name`
- `capacity`
- `whitelist`
- `fee`
- `selection`

Extracted all setup and server starting logic from the `start` method.

### Issues

closes #8 

### Example

@mpetrun5 @mpetrunic Do you think these **[OPTIONAL]** and **[REQUIRED]** prefixes are needed?

![image](https://user-images.githubusercontent.com/23664028/93475523-0143ff00-f8f9-11ea-9309-47074b46a528.png)

2020-09-17 20:12 UTC, mpetrunic requested changes

2020-09-17 20:12 UTC, mpetrunic commented on cmd/start.go
> +		10,
probably should be unlimited by default

2020-09-17 20:12 UTC, mpetrunic commented on cmd/start.go
> +		0,
we can make 10% by default so it's not required

2020-09-17 20:12 UTC, mpetrunic commented on cmd/start.go
> +	}, "4000")
port should also be cli flag

2020-09-17 20:12 UTC, mpetrunic commented on internal/loadbalancer/server.go
> +func StartLoadBalancerServer(props Properties, port string) {
port should be number?

2020-09-17 20:12 UTC, mpetrunic commented on internal/loadbalancer/server.go
> +	log.Println("Starting vedran load balancer on port :4000...")
use real port value instead of hardoded 4000

2020-09-17 20:12 UTC, mpetrunic commented on cmd/start.go
> +		0,
also validate fee is between 0 and 100

2020-09-17 20:12 UTC, mpetrunic commented on cmd/start.go
> +		0,
or 0 -1 since you are using float32

2020-09-17 20:12 UTC, mpetrunic commented on cmd/start.go
> +		10,
ensure it's higher than -1, we can use -1 as unlimited

2020-09-18 08:21 UTC, mpetrunic approved these changes, later dismissed

2020-09-18 08:27 UTC, mpetrun5 approved these changes

2020-09-18 08:28 UTC, mpetrunic approved these changes

2020-09-18 08:28 UTC, merged