Ping endpoint
NodeFactoryIo/vedran pull request #25
Opened 2020-09-18 13:10 UTC by MakMuftic

### Changes

- Implemented `POST  /api/vi1/nodes/pings` endpoint. Body should be empty, and only `X-Auth-Token` header set, @mpetrun5 
- Implemented auth middleware and refactored claims to use custom _structure_
- Added test for ping endpoint and auth middleware

### Issues

closes #3 

### TODO

This is a basic implementation of the ping endpoint as it only saves the latest timestamp for the specified node. Additional logic should be implemented to check when was the last ping and record if there were any downtime, also some reoccurring job should be implemented to check if some node hasn't invoked the ping endpoint for a longer time. This was out of the scope for this PR, especially with all refactoring and addition of auth related code in this PR.

2020-09-18 13:15 UTC, mpetrunic requested changes

2020-09-18 13:15 UTC, mpetrunic commented on internal/auth/middleware.go
> +		log.Println(err)
error description pls

2020-09-19 10:56 UTC, mpetrunic approved these changes

2020-09-21 09:59 UTC, mpetrun5 approved these changes

2020-09-21 10:04 UTC, merged