Route rpc requests
NodeFactoryIo/vedran pull request #47
Opened 2020-10-06 14:37 UTC by mpetrun5

**Short description of work done**
Route RPC requests to nodes

### PR Checklist
- [x] I have run linter localy
- [x] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master

### Changes
 - Added root endpoint (/) that routes rpc requests and checks if request and response are valid
 - Support batching

# TODO
We should support compressed requests and response ---> #46

### Issues
Closes: #38

2020-10-06 14:38 UTC, mpetrun5 commented on internal/repositories/node.go
> +	q := r.db.Select(q.Lte("Cooldown", 0))
This is just temporary until we have proper cooldown logic

2020-10-07 07:59 UTC, mpetrunic approved these changes

2020-10-07 08:43 UTC, MakMuftic requested changes

2020-10-07 08:43 UTC, MakMuftic commented on internal/controllers/rpc.go
> +	reqBody, _ := ioutil.ReadAll(r.Body)
Are you sure that you can ignore this error ?

2020-10-07 08:43 UTC, MakMuftic commented on internal/controllers/rpc.go
> +		log.Errorf("Invalid request")
I think you should check for single and batch or just let node to propagate error

2020-10-07 11:19 UTC, MakMuftic approved these changes

2020-10-07 13:36 UTC, merged