Return port in register response
NodeFactoryIo/vedran pull request #65
Opened 2020-10-14 08:42 UTC by mpetrun5

**Short description of work done**

Return aquired port in register response

### PR Checklist

- [x] I have run linter localy
- [x] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master
- [ ] Updated CHANGELOG.md

### Changes

- move port pool outside tunnel and add it to load balancer configuration
- aquire port after register and return in response

### Issues

Closes: #64

2020-10-14 13:44 UTC, mpetrun5 commented
@MakMuftic @mpetrunic 
I think this is ready for review

2020-10-14 14:32 UTC, MakMuftic requested changes

2020-10-14 14:32 UTC, MakMuftic commented on pkg/http-tunnel/server/addrpool.go
> +	assignedPort = 0
Why first define `assignedPort` and then initialize it? I think that `assignedPort := 0` is the same thing.

2020-10-15 07:08 UTC, MakMuftic approved these changes

2020-10-15 07:33 UTC, mpetrunic approved these changes

2020-10-15 07:33 UTC, merged